### ISSUE TITLE
uformatter?

### ISSUE THREAD

**Issue by darkhs** [re22/Kitty#1]
Fala renan... esse programa vai ser igual o uformatter que você postou no fórum wc um tempo atrás? abç

**Comment by re22** [comment]
Olá @darkhs :metal: ,
Em partes, sim. Mas o uFormatter fazia somente o básico, eu tinha escrito ele em menos de semana.
Então estou escrevendo esse, tornando-o mais organizado e algumas funções extras e.g enviar imagens diretamente para o Imgur, hospedar os arquivos, criar o scan, tudo sem precisar abrir o navegador.
